# -*- coding: utf-8 -*-
"""dogvscat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zN17Eu0h040On-r6Q_eZg6Bf8Fm6S3qG
"""

!wget https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip

!unzip kagglecatsanddogs_5340.zip

"""# Import Modules"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
import os
import tqdm
import random
from keras.preprocessing.image import load_img
warnings.filterwarnings('ignore')

"""# Creating DataFrame for Input and Output"""

input_path = []
label = []

for class_name in os.listdir("PetImages"):
    for path in os.listdir("PetImages/"+class_name):
        if class_name == 'Cat':
            label.append(0)
        else:
            label.append(1)
        input_path.append(os.path.join("PetImages", class_name, path))
print(input_path[0], label[0])
print(input_path[10], label[10])

# Now we create the dataframe for processing
df = pd.DataFrame()
df['images'] = input_path
df['label'] = label
df = df.sample(frac=1).reset_index(drop=True)#to shuffle the data
df.head()

#remove any files in the data set that are not image data to avoid errors
for i in df['images']:
    if '.jpg' not in i:
        print(i)

import PIL
l = []
for image in df['images']:
    try:
        img = PIL.Image.open(image)
    except:
        l.append(image)
l

# delete db files
df = df[df['images']!='PetImages/Dog/Thumbs.db']
df = df[df['images']!='PetImages/Cat/Thumbs.db']
df = df[df['images']!='PetImages/Cat/666.jpg']
df = df[df['images']!='PetImages/Dog/11702.jpg']
len(df)

"""# Exploratory Data Analysis"""

# to display grid of images
plt.figure(figsize=(25,25))
temp = df[df['label']==1]['images']
start = random.randint(0, len(temp))
files = temp[start:start+25]

for index, file in enumerate(files):
    plt.subplot(5,5, index+1)
    img = load_img(file)
    img = np.array(img)
    plt.imshow(img)
    plt.title('Dogs')
    plt.axis('off')

# to display grid of images
plt.figure(figsize=(25,25))
temp = df[df['label']==0]['images']
start = random.randint(0, len(temp))
files = temp[start:start+25]

for index, file in enumerate(files):
    plt.subplot(5,5, index+1)
    img = load_img(file)
    img = np.array(img)
    plt.imshow(img)
    plt.title('Cats')
    plt.axis('off')

"""# Create DataGenerator for the Images"""

df['label'] = df['label'].astype('str')
df.head()

# input split
from sklearn.model_selection import train_test_split
train, test = train_test_split(df, test_size=0.2, random_state=42)

train.head()

test.head()

from keras.preprocessing.image import ImageDataGenerator
train_generator = ImageDataGenerator(
    rescale = 1./255,  # normalization of images
    rotation_range = 40, # augmention of images to avoid overfitting
    shear_range = 0.2,
    zoom_range = 0.2,
    horizontal_flip = True,
    fill_mode = 'nearest'
)
val_generator = ImageDataGenerator(rescale = 1./255)

train_iterator = train_generator.flow_from_dataframe(
    train,x_col='images',
    y_col='label',
    target_size=(128,128),
    batch_size=512,
    class_mode='binary'
)

val_iterator = val_generator.flow_from_dataframe(
    test,x_col='images',
    y_col='label',
    target_size=(128,128),
    batch_size=512,
    class_mode='binary'
)

"""# Model Creation"""

from keras import Sequential
from keras.layers import Conv2D, MaxPool2D, Flatten, Dense

model = Sequential([
            Conv2D(16, (3,3), activation='relu', input_shape=(128,128,3)),
            MaxPool2D((2,2)),
            Conv2D(32, (3,3), activation='relu'),
            MaxPool2D((2,2)),
            Conv2D(64, (3,3), activation='relu'),
            MaxPool2D((2,2)),
            Flatten(),
            Dense(512, activation='relu'),
            Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

history = model.fit(train_iterator, epochs=10, validation_data=val_iterator)

"""# Visualization of results"""

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
epochs = range(len(acc))

plt.plot(epochs, acc, 'b', label='Training Accuracy')
plt.plot(epochs, val_acc, 'r', label='Validation Accuracy')
plt.title('Accuracy Graph')
plt.legend()
plt.figure()

loss = history.history['loss']
val_loss = history.history['val_loss']
plt.plot(epochs, loss, 'b', label='Training Loss')
plt.plot(epochs, val_loss, 'r', label='Validation Loss')
plt.title('Loss Graph')
plt.legend()
plt.show()

"""# Test with Real Image"""

import numpy as np
from keras.preprocessing.image import load_img
import matplotlib.pyplot as plt

# Assuming you have a loaded model
# model = ...

# Path of the image
image_path = "test_img.jpeg"

# Load and preprocess the image
img = load_img(image_path, target_size=(128, 128))
img_array = np.array(img)
img_array = img_array / 255.0  # Normalize the image
img_array = img_array.reshape(1, 128, 128, 3)  # Reshape for prediction

# Make a prediction
pred = model.predict(img_array)

# Determine the label based on the prediction
label = 'Dog' if pred[0] > 0.5 else 'Cat'

# Display the image
plt.imshow(img)
plt.axis('off')
plt.show()


print("\nLabel:", label)

import numpy as np
from keras.preprocessing.image import load_img
import matplotlib.pyplot as plt

# Assuming you have a loaded model
# model = ...

# Path of the image
image_path = "test_img1.jpg"

# Load and preprocess the image
img = load_img(image_path, target_size=(128, 128))
img_array = np.array(img)
img_array = img_array / 255.0  # Normalize the image
img_array = img_array.reshape(1, 128, 128, 3)  # Reshape for prediction

# Make a prediction
pred = model.predict(img_array)

# Determine the label based on the prediction
label = 'Dog' if pred[0] > 0.5 else 'Cat'

# Display the image
plt.imshow(img)
plt.axis('off')
plt.show()


print("\nLabel:", label)